apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "paperless-ai.fullname" . }}
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "paperless-ai.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "paperless-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "paperless-ai.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- with .Values.envs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: data
              mountPath: /app/data

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "paperless-ai.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.data.accessMode | default "ReadWriteOnce" }}
        {{- if .Values.persistence.data.storageClassName }}
        storageClassName: {{ .Values.persistence.data.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | default "5Gi" }}
